// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNehkdARdFYJKCNIaSB4oME-ODxgprO9Y',
    appId: '1:800541664032:web:b69a735c932140b5d7ad45',
    messagingSenderId: '800541664032',
    projectId: 'cuisine-mada',
    authDomain: 'cuisine-mada.firebaseapp.com',
    storageBucket: 'cuisine-mada.firebasestorage.app',
    measurementId: 'G-LMW08E55BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo54UkwbH3NOXf2zsxbJeZIWB0-MnZS1M',
    appId: '1:800541664032:android:906be0f7f0d3789cd7ad45',
    messagingSenderId: '800541664032',
    projectId: 'cuisine-mada',
    storageBucket: 'cuisine-mada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC258IWMV_PRoOZPQwtNEElwYBb-PoN4nU',
    appId: '1:800541664032:ios:ec9f3097b927eccfd7ad45',
    messagingSenderId: '800541664032',
    projectId: 'cuisine-mada',
    storageBucket: 'cuisine-mada.firebasestorage.app',
    iosBundleId: 'com.cuisinemada.cuisineMada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC258IWMV_PRoOZPQwtNEElwYBb-PoN4nU',
    appId: '1:800541664032:ios:ec9f3097b927eccfd7ad45',
    messagingSenderId: '800541664032',
    projectId: 'cuisine-mada',
    storageBucket: 'cuisine-mada.firebasestorage.app',
    iosBundleId: 'com.cuisinemada.cuisineMada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNehkdARdFYJKCNIaSB4oME-ODxgprO9Y',
    appId: '1:800541664032:web:830f9874d4b46052d7ad45',
    messagingSenderId: '800541664032',
    projectId: 'cuisine-mada',
    authDomain: 'cuisine-mada.firebaseapp.com',
    storageBucket: 'cuisine-mada.firebasestorage.app',
    measurementId: 'G-F0KND3FDCD',
  );
}
