import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:cuisine_mada/firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  await seedRecipes();
  print('✅ Les 50 recettes ont été ajoutées !');
}

Future<void> seedRecipes() async {
  final firestore = FirebaseFirestore.instance;
  final recipes = _getRecipes();

  for (final recipe in recipes) {
    print('Ajout : ${recipe['name']}');
    final ingredients = recipe['ingredients'] as List<Map<String, dynamic>>;
    final recipeData = Map<String, dynamic>.from(recipe)
      ..remove('ingredients');

    final ref = await firestore.collection('recipes').add(recipeData);

    for (final ing in ingredients) {
      await ref.collection('ingredients').add(ing);
    }
  }
}

Map<String, dynamic> _recipe({
  required String name,
  required String description,
  required String emoji,
  required int prepMinutes,
  required int cookMinutes,
  required int basePersons,
  required bool isHalal,
  required bool isVegetarian,
  required List<String> tags,
  required List<Map<String, dynamic>> ingredients,
}) {
  final totalCost = ingredients.fold<double>(0, (sum, ing) {
    final qty = (ing['quantity'] as num).toDouble();
    final price = (ing['pricePerUnit'] as num).toDouble();
    return sum + (qty * price);
  });

  return {
    'name': name,
    'description': description,
    'emoji': emoji,
    'preparationMinutes': prepMinutes,
    'cookMinutes': cookMinutes,
    'basePersons': basePersons,
    'estimatedCost': totalCost.toInt(),
    'isHalal': isHalal,
    'isVegetarian': isVegetarian,
    'isValidated': true,
    'imageUrl': '',
    'createdByUserName': '',
    'averageRating': '4.5',
    'tags': tags,
    'createdAt': FieldValue.serverTimestamp(),
    'ingredients': ingredients,
  };
}

Map<String, dynamic> _ing(
    String name, double quantity, String unit, double pricePerUnit) {
  return {
    'name': name,
    'quantity': quantity,
    'unit': unit,
    'pricePerUnit': pricePerUnit,
  };
}

List<Map<String, dynamic>> _getRecipes() {
  return [
    _recipe(
      name: 'Romazava zébu brèdes mafana',
      description: 'Zébu mijoté avec brèdes mafana croquantes',
      emoji: '🍲',
      prepMinutes: 20,
      cookMinutes: 80,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Traditionnel', 'Familial'],
      ingredients: [
        _ing('Zébu', 800, 'g', 20),
        _ing('Brèdes mafana', 500, 'g', 2),
        _ing('Oignon', 1, 'pièce(s)', 500),
        _ing('Gingembre', 20, 'g', 5),
        _ing('Tomate', 2, 'pièce(s)', 800),
        _ing('Huile', 20, 'ml', 8),
        _ing('Sel', 1, 'c.à.c', 1),
      ],
    ),
    _recipe(
      name: 'Vary amin\'anana brèdes cresson',
      description: 'Riz aux brèdes cresson et gingembre',
      emoji: '🥗',
      prepMinutes: 10,
      cookMinutes: 30,
      basePersons: 4,
      isHalal: true,
      isVegetarian: true,
      tags: ['Rapide', 'Économique', 'Végétarien'],
      ingredients: [
        _ing('Riz', 200, 'g', 3.8),
        _ing('Brèdes cresson', 300, 'g', 2),
        _ing('Gingembre', 10, 'g', 5),
        _ing('Sel', 1, 'c.à.c', 1),
      ],
    ),
    _recipe(
      name: 'Akoho sy voanio',
      description: 'Poulet au lait de coco parfumé',
      emoji: '🐔',
      prepMinutes: 15,
      cookMinutes: 30,
      basePersons: 4,
      isHalal: true,
      isVegetarian: false,
      tags: ['Halal', 'Familial', 'Savoureux'],
      ingredients: [
        _ing('Poulet', 1000, 'g', 15),
        _ing('Lait de coco', 300, 'ml', 3),
        _ing('Oignon', 2, 'pièce(s)', 500),
        _ing('Ail', 2, 'pièce(s)', 1),
        _ing('Poivre', 1, 'c.à.s', 20),
      ],
    ),
    _recipe(
      name: 'Ravitoto sy henakisoa',
      description: 'Feuilles de manioc pilées avec porc',
      emoji: '🍃',
      prepMinutes: 30,
      cookMinutes: 120,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Traditionnel', 'Familial'],
      ingredients: [
        _ing('Porc', 800, 'g', 18),
        _ing('Feuilles de manioc (ravitoto)', 500, 'g', 5),
        _ing('Oignon', 1, 'pièce(s)', 500),
        _ing('Ail', 3, 'pièce(s)', 1),
        _ing('Huile', 50, 'ml', 8),
      ],
    ),
    _recipe(
      name: 'Romazava tripes brèdes cresson',
      description: 'Tripes mijotées avec brèdes cresson croquantes',
      emoji: '🍲',
      prepMinutes: 25,
      cookMinutes: 90,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Traditionnel'],
      ingredients: [
        _ing('Tripes', 1000, 'g', 15),
        _ing('Brèdes cresson', 400, 'g', 2),
        _ing('Gingembre', 20, 'g', 5),
        _ing('Tomate', 1, 'pièce(s)', 800),
        _ing('Sel', 1, 'c.à.c', 1),
      ],
    ),
    _recipe(
      name: 'Carry zébu carottes',
      description: 'Curry de zébu aux carottes et pommes de terre',
      emoji: '🥕',
      prepMinutes: 20,
      cookMinutes: 60,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Familial', 'Savoureux'],
      ingredients: [
        _ing('Zébu', 700, 'g', 20),
        _ing('Carottes', 300, 'g', 2),
        _ing('Pommes de terre', 400, 'g', 2.5),
        _ing('Oignon', 1, 'pièce(s)', 500),
        _ing('Ail', 2, 'pièce(s)', 1),
      ],
    ),
    _recipe(
      name: 'Tilapia frit brèdes mafana',
      description: 'Tilapia frit servi avec brèdes mafana fraîches',
      emoji: '🐟',
      prepMinutes: 10,
      cookMinutes: 20,
      basePersons: 4,
      isHalal: true,
      isVegetarian: false,
      tags: ['Halal', 'Rapide', 'Économique'],
      ingredients: [
        _ing('Tilapia', 800, 'g', 12),
        _ing('Brèdes mafana', 200, 'g', 2),
        _ing('Citron', 1, 'pièce(s)', 300),
        _ing('Ail', 2, 'pièce(s)', 1),
        _ing('Huile', 50, 'ml', 8),
      ],
    ),
    _recipe(
      name: 'Poulet haricots blancs tomates',
      description: 'Poulet mijoté aux haricots blancs et tomates',
      emoji: '🍗',
      prepMinutes: 15,
      cookMinutes: 45,
      basePersons: 4,
      isHalal: true,
      isVegetarian: false,
      tags: ['Halal', 'Familial'],
      ingredients: [
        _ing('Poulet', 800, 'g', 15),
        _ing('Haricots blancs', 300, 'g', 3),
        _ing('Tomate', 2, 'pièce(s)', 800),
        _ing('Oignon', 1, 'pièce(s)', 500),
      ],
    ),
    _recipe(
      name: 'Romazava zébu brèdes anamalao',
      description: 'Romazava authentique au zébu et brèdes anamalao',
      emoji: '🍲',
      prepMinutes: 20,
      cookMinutes: 80,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Traditionnel', 'Familial'],
      ingredients: [
        _ing('Zébu', 800, 'g', 20),
        _ing('Brèdes anamalao', 500, 'g', 2),
        _ing('Gingembre', 20, 'g', 5),
        _ing('Oignon', 1, 'pièce(s)', 500),
      ],
    ),
    _recipe(
      name: 'Vary tripes brèdes',
      description: 'Riz aux tripes et brèdes mijotées',
      emoji: '🍚',
      prepMinutes: 15,
      cookMinutes: 40,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Économique'],
      ingredients: [
        _ing('Riz', 200, 'g', 3.8),
        _ing('Tripes', 500, 'g', 15),
        _ing('Brèdes', 200, 'g', 2),
        _ing('Gingembre', 10, 'g', 5),
      ],
    ),
    _recipe(
      name: 'Kimo zébu oignons',
      description: 'Foie de zébu sauté aux oignons et gingembre',
      emoji: '🥩',
      prepMinutes: 25,
      cookMinutes: 90,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Traditionnel'],
      ingredients: [
        _ing('Zébu', 1000, 'g', 20),
        _ing('Oignon', 2, 'pièce(s)', 500),
        _ing('Gingembre', 20, 'g', 5),
        _ing('Sel', 1, 'c.à.c', 1),
      ],
    ),
    _recipe(
      name: 'Crevettes coco',
      description: 'Crevettes sautées au lait de coco et gingembre',
      emoji: '🦐',
      prepMinutes: 20,
      cookMinutes: 25,
      basePersons: 4,
      isHalal: true,
      isVegetarian: false,
      tags: ['Halal', 'Rapide', 'Savoureux'],
      ingredients: [
        _ing('Crevettes', 500, 'g', 25),
        _ing('Lait de coco', 200, 'ml', 3),
        _ing('Ail', 2, 'pièce(s)', 1),
        _ing('Gingembre', 10, 'g', 5),
      ],
    ),
    _recipe(
      name: 'Zébu haricots rouges',
      description: 'Zébu mijoté aux haricots rouges et tomates',
      emoji: '🫘',
      prepMinutes: 20,
      cookMinutes: 60,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Familial', 'Économique'],
      ingredients: [
        _ing('Zébu', 500, 'g', 20),
        _ing('Haricots rouges', 400, 'g', 3),
        _ing('Tomate', 2, 'pièce(s)', 800),
        _ing('Oignon', 1, 'pièce(s)', 500),
      ],
    ),
    _recipe(
      name: 'Oeufs brèdes tomates',
      description: 'Oeufs brouillés aux brèdes fraîches et tomates',
      emoji: '🍳',
      prepMinutes: 10,
      cookMinutes: 15,
      basePersons: 2,
      isHalal: true,
      isVegetarian: true,
      tags: ['Rapide', 'Économique', 'Végétarien', 'Halal'],
      ingredients: [
        _ing('Oeufs', 4, 'pièce(s)', 500),
        _ing('Brèdes', 200, 'g', 2),
        _ing('Tomates', 200, 'g', 0.8),
        _ing('Oignon', 1, 'pièce(s)', 500),
      ],
    ),
    _recipe(
      name: 'Ravitoto zébu',
      description: 'Feuilles de manioc pilées au zébu',
      emoji: '🍃',
      prepMinutes: 30,
      cookMinutes: 110,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Traditionnel', 'Familial'],
      ingredients: [
        _ing('Zébu', 800, 'g', 20),
        _ing('Feuilles de manioc (ravitoto)', 500, 'g', 5),
        _ing('Ail', 2, 'pièce(s)', 1),
      ],
    ),
    _recipe(
      name: 'Porc carottes gingembre',
      description: 'Porc mijoté aux carottes et gingembre',
      emoji: '🥕',
      prepMinutes: 20,
      cookMinutes: 50,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Familial'],
      ingredients: [
        _ing('Porc', 700, 'g', 18),
        _ing('Carottes', 300, 'g', 2),
        _ing('Gingembre', 10, 'g', 5),
        _ing('Oignon', 1, 'pièce(s)', 500),
      ],
    ),
    _recipe(
      name: 'Capitaine frit haricots',
      description: 'Capitaine frit avec haricots et tomates',
      emoji: '🐠',
      prepMinutes: 15,
      cookMinutes: 35,
      basePersons: 4,
      isHalal: true,
      isVegetarian: false,
      tags: ['Halal', 'Économique'],
      ingredients: [
        _ing('Capitaine', 600, 'g', 13),
        _ing('Haricots', 300, 'g', 3),
        _ing('Tomate', 1, 'pièce(s)', 800),
      ],
    ),
    _recipe(
      name: 'Poulet lentilles oignons',
      description: 'Poulet aux lentilles et oignons dorés',
      emoji: '🍗',
      prepMinutes: 25,
      cookMinutes: 70,
      basePersons: 4,
      isHalal: true,
      isVegetarian: false,
      tags: ['Halal', 'Familial'],
      ingredients: [
        _ing('Poulet', 800, 'g', 15),
        _ing('Lentilles', 300, 'g', 3.5),
        _ing('Oignon', 2, 'pièce(s)', 500),
      ],
    ),
    _recipe(
      name: 'Tripes gingembre sel',
      description: 'Tripes mijotées au gingembre et oignons',
      emoji: '🍲',
      prepMinutes: 25,
      cookMinutes: 90,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Traditionnel'],
      ingredients: [
        _ing('Tripes', 800, 'g', 15),
        _ing('Gingembre', 20, 'g', 5),
        _ing('Sel', 1, 'c.à.c', 1),
        _ing('Oignon', 1, 'pièce(s)', 500),
      ],
    ),
    _recipe(
      name: 'Calamars ail poivrons',
      description: 'Calamars sautés à l\'ail et poivrons',
      emoji: '🦑',
      prepMinutes: 15,
      cookMinutes: 20,
      basePersons: 4,
      isHalal: true,
      isVegetarian: false,
      tags: ['Halal', 'Rapide', 'Savoureux'],
      ingredients: [
        _ing('Calamars', 400, 'g', 25),
        _ing('Poivrons', 200, 'g', 3),
        _ing('Ail', 2, 'pièce(s)', 1),
      ],
    ),
    _recipe(
      name: 'Romazava porc brèdes',
      description: 'Romazava au porc et brèdes mafana',
      emoji: '🍲',
      prepMinutes: 20,
      cookMinutes: 80,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Traditionnel', 'Familial'],
      ingredients: [
        _ing('Porc', 700, 'g', 18),
        _ing('Brèdes mafana', 400, 'g', 2),
        _ing('Gingembre', 20, 'g', 5),
        _ing('Tomate', 1, 'pièce(s)', 800),
      ],
    ),
    _recipe(
      name: 'Porc haricots coco',
      description: 'Porc aux haricots et lait de coco',
      emoji: '🥥',
      prepMinutes: 20,
      cookMinutes: 50,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Savoureux', 'Familial'],
      ingredients: [
        _ing('Porc', 600, 'g', 18),
        _ing('Haricots', 300, 'g', 3),
        _ing('Lait de coco', 200, 'ml', 3),
      ],
    ),
    _recipe(
      name: 'Tilapia frit brèdes cresson',
      description: 'Tilapia frit avec brèdes cresson fraîches',
      emoji: '🐟',
      prepMinutes: 10,
      cookMinutes: 20,
      basePersons: 4,
      isHalal: true,
      isVegetarian: false,
      tags: ['Halal', 'Rapide', 'Économique'],
      ingredients: [
        _ing('Tilapia', 600, 'g', 12),
        _ing('Brèdes cresson', 300, 'g', 2),
        _ing('Citron', 1, 'pièce(s)', 300),
        _ing('Huile', 50, 'ml', 8),
      ],
    ),
    _recipe(
      name: 'Poulet ravitoto',
      description: 'Poulet mijoté aux feuilles de manioc pilées',
      emoji: '🍃',
      prepMinutes: 30,
      cookMinutes: 100,
      basePersons: 4,
      isHalal: true,
      isVegetarian: false,
      tags: ['Halal', 'Traditionnel'],
      ingredients: [
        _ing('Poulet', 700, 'g', 15),
        _ing('Feuilles de manioc (ravitoto)', 400, 'g', 5),
        _ing('Ail', 2, 'pièce(s)', 1),
      ],
    ),
    _recipe(
      name: 'Zébu oeufs carottes',
      description: 'Zébu aux carottes et oeufs pochés',
      emoji: '🥕',
      prepMinutes: 20,
      cookMinutes: 45,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Familial'],
      ingredients: [
        _ing('Zébu', 600, 'g', 20),
        _ing('Oeufs', 4, 'pièce(s)', 500),
        _ing('Carottes', 300, 'g', 2),
      ],
    ),
    _recipe(
      name: 'Tripes haricots blancs',
      description: 'Tripes mijotées aux haricots blancs',
      emoji: '🫘',
      prepMinutes: 25,
      cookMinutes: 80,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Économique'],
      ingredients: [
        _ing('Tripes', 700, 'g', 15),
        _ing('Haricots blancs', 300, 'g', 3),
        _ing('Gingembre', 10, 'g', 5),
      ],
    ),
    _recipe(
      name: 'Crevettes citron ail',
      description: 'Crevettes marinées au citron et ail',
      emoji: '🦐',
      prepMinutes: 15,
      cookMinutes: 20,
      basePersons: 4,
      isHalal: true,
      isVegetarian: false,
      tags: ['Halal', 'Rapide', 'Savoureux'],
      ingredients: [
        _ing('Crevettes', 400, 'g', 25),
        _ing('Citron', 2, 'pièce(s)', 300),
        _ing('Ail', 2, 'pièce(s)', 1),
      ],
    ),
    _recipe(
      name: 'Porc oeufs tomates',
      description: 'Porc sauté aux oeufs brouillés et tomates',
      emoji: '🍳',
      prepMinutes: 15,
      cookMinutes: 30,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Rapide', 'Économique'],
      ingredients: [
        _ing('Porc', 500, 'g', 18),
        _ing('Oeufs', 2, 'pièce(s)', 500),
        _ing('Tomates', 2, 'pièce(s)', 800),
      ],
    ),
    _recipe(
      name: 'Capitaine coco gingembre',
      description: 'Capitaine au lait de coco et gingembre',
      emoji: '🐠',
      prepMinutes: 20,
      cookMinutes: 30,
      basePersons: 4,
      isHalal: true,
      isVegetarian: false,
      tags: ['Halal', 'Savoureux'],
      ingredients: [
        _ing('Capitaine', 600, 'g', 13),
        _ing('Lait de coco', 250, 'ml', 3),
        _ing('Gingembre', 10, 'g', 5),
      ],
    ),
    _recipe(
      name: 'Poulet pois chiches',
      description: 'Poulet mijoté aux pois chiches et oignons',
      emoji: '🍗',
      prepMinutes: 20,
      cookMinutes: 50,
      basePersons: 4,
      isHalal: true,
      isVegetarian: false,
      tags: ['Halal', 'Familial'],
      ingredients: [
        _ing('Poulet', 700, 'g', 15),
        _ing('Pois chiches', 300, 'g', 4),
        _ing('Oignon', 1, 'pièce(s)', 500),
      ],
    ),
    _recipe(
      name: 'Romazava zébu brèdes vertes',
      description: 'Romazava classique au zébu et brèdes vertes',
      emoji: '🍲',
      prepMinutes: 20,
      cookMinutes: 80,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Traditionnel', 'Familial'],
      ingredients: [
        _ing('Zébu', 700, 'g', 20),
        _ing('Brèdes vertes', 500, 'g', 2),
        _ing('Oignon', 1, 'pièce(s)', 500),
        _ing('Gingembre', 10, 'g', 5),
      ],
    ),
    _recipe(
      name: 'Moules poivrons',
      description: 'Moules sautées aux poivrons et ail',
      emoji: '🦪',
      prepMinutes: 15,
      cookMinutes: 20,
      basePersons: 4,
      isHalal: true,
      isVegetarian: false,
      tags: ['Halal', 'Rapide'],
      ingredients: [
        _ing('Moules', 500, 'g', 25),
        _ing('Poivrons', 300, 'g', 3),
        _ing('Ail', 2, 'pièce(s)', 1),
      ],
    ),
    _recipe(
      name: 'Zébu lentilles tomates',
      description: 'Zébu mijoté aux lentilles et tomates',
      emoji: '🫘',
      prepMinutes: 20,
      cookMinutes: 60,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Familial', 'Économique'],
      ingredients: [
        _ing('Zébu', 600, 'g', 20),
        _ing('Lentilles', 300, 'g', 3.5),
        _ing('Tomates', 2, 'pièce(s)', 800),
      ],
    ),
    _recipe(
      name: 'Oeufs aubergines',
      description: 'Omelette aux aubergines et oignons',
      emoji: '🍆',
      prepMinutes: 15,
      cookMinutes: 25,
      basePersons: 2,
      isHalal: true,
      isVegetarian: true,
      tags: ['Rapide', 'Économique', 'Végétarien', 'Halal'],
      ingredients: [
        _ing('Oeufs', 4, 'pièce(s)', 500),
        _ing('Aubergines', 300, 'g', 1.5),
        _ing('Oignon', 1, 'pièce(s)', 500),
      ],
    ),
    _recipe(
      name: 'Tripes ravitoto',
      description: 'Tripes mijotées aux feuilles de manioc pilées',
      emoji: '🍃',
      prepMinutes: 30,
      cookMinutes: 110,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Traditionnel'],
      ingredients: [
        _ing('Tripes', 800, 'g', 15),
        _ing('Feuilles de manioc (ravitoto)', 500, 'g', 5),
        _ing('Oignon', 1, 'pièce(s)', 500),
      ],
    ),
    _recipe(
      name: 'Poulet courgettes haricots',
      description: 'Poulet aux courgettes et haricots mijotés',
      emoji: '🍗',
      prepMinutes: 20,
      cookMinutes: 50,
      basePersons: 4,
      isHalal: true,
      isVegetarian: false,
      tags: ['Halal', 'Familial'],
      ingredients: [
        _ing('Poulet', 600, 'g', 15),
        _ing('Courgettes', 300, 'g', 2),
        _ing('Haricots', 200, 'g', 3),
      ],
    ),
    _recipe(
      name: 'Porc coco gingembre',
      description: 'Porc mijoté au lait de coco et gingembre',
      emoji: '🥥',
      prepMinutes: 20,
      cookMinutes: 40,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Savoureux'],
      ingredients: [
        _ing('Porc', 600, 'g', 18),
        _ing('Lait de coco', 200, 'ml', 3),
        _ing('Gingembre', 10, 'g', 5),
      ],
    ),
    _recipe(
      name: 'Tilapia frit oeufs',
      description: 'Tilapia frit accompagné d\'oeufs',
      emoji: '🐟',
      prepMinutes: 15,
      cookMinutes: 25,
      basePersons: 4,
      isHalal: true,
      isVegetarian: false,
      tags: ['Halal', 'Rapide', 'Économique'],
      ingredients: [
        _ing('Tilapia', 500, 'g', 12),
        _ing('Oeufs', 3, 'pièce(s)', 500),
      ],
    ),
    _recipe(
      name: 'Calamars citron légumes',
      description: 'Calamars sautés au citron et légumes',
      emoji: '🦑',
      prepMinutes: 15,
      cookMinutes: 20,
      basePersons: 4,
      isHalal: true,
      isVegetarian: false,
      tags: ['Halal', 'Rapide'],
      ingredients: [
        _ing('Calamars', 400, 'g', 25),
        _ing('Carottes', 200, 'g', 2),
        _ing('Citron', 1, 'pièce(s)', 300),
      ],
    ),
    _recipe(
      name: 'Zébu brèdes mafana romazava',
      description: 'Romazava express au zébu et brèdes mafana',
      emoji: '🍲',
      prepMinutes: 20,
      cookMinutes: 45,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Traditionnel', 'Rapide'],
      ingredients: [
        _ing('Zébu', 500, 'g', 20),
        _ing('Brèdes mafana', 400, 'g', 2),
        _ing('Tomate', 1, 'pièce(s)', 800),
      ],
    ),
    _recipe(
      name: 'Tripes carottes',
      description: 'Tripes mijotées aux carottes',
      emoji: '🥕',
      prepMinutes: 20,
      cookMinutes: 60,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Économique'],
      ingredients: [
        _ing('Tripes', 600, 'g', 15),
        _ing('Carottes', 400, 'g', 2),
        _ing('Sel', 1, 'c.à.c', 1),
      ],
    ),
    _recipe(
      name: 'Crevettes brèdes crues',
      description: 'Crevettes sautées servies avec brèdes fraîches',
      emoji: '🦐',
      prepMinutes: 10,
      cookMinutes: 15,
      basePersons: 4,
      isHalal: true,
      isVegetarian: false,
      tags: ['Halal', 'Rapide'],
      ingredients: [
        _ing('Crevettes', 400, 'g', 25),
        _ing('Brèdes', 300, 'g', 2),
        _ing('Ail', 2, 'pièce(s)', 1),
      ],
    ),
    _recipe(
      name: 'Poulet ravitoto feuilles',
      description: 'Poulet longuement mijoté au ravitoto',
      emoji: '🍃',
      prepMinutes: 30,
      cookMinutes: 100,
      basePersons: 4,
      isHalal: true,
      isVegetarian: false,
      tags: ['Halal', 'Traditionnel'],
      ingredients: [
        _ing('Poulet', 700, 'g', 15),
        _ing('Feuilles de manioc (ravitoto)', 400, 'g', 5),
      ],
    ),
    _recipe(
      name: 'Porc haricots verts',
      description: 'Porc mijoté aux haricots verts',
      emoji: '🫛',
      prepMinutes: 20,
      cookMinutes: 50,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Familial', 'Économique'],
      ingredients: [
        _ing('Porc', 500, 'g', 18),
        _ing('Haricots verts', 300, 'g', 2.5),
      ],
    ),
    _recipe(
      name: 'Capitaine frit tomates',
      description: 'Capitaine frit avec sauce tomates maison',
      emoji: '🐠',
      prepMinutes: 15,
      cookMinutes: 25,
      basePersons: 4,
      isHalal: true,
      isVegetarian: false,
      tags: ['Halal', 'Rapide'],
      ingredients: [
        _ing('Capitaine', 500, 'g', 13),
        _ing('Tomates', 200, 'g', 0.8),
      ],
    ),
    _recipe(
      name: 'Omelette poivrons',
      description: 'Omelette colorée aux poivrons',
      emoji: '🫑',
      prepMinutes: 15,
      cookMinutes: 20,
      basePersons: 2,
      isHalal: true,
      isVegetarian: true,
      tags: ['Rapide', 'Économique', 'Végétarien', 'Halal'],
      ingredients: [
        _ing('Oeufs', 4, 'pièce(s)', 500),
        _ing('Poivrons', 300, 'g', 3),
      ],
    ),
    _recipe(
      name: 'Haricots tripes',
      description: 'Haricots mijotés aux tripes',
      emoji: '🫘',
      prepMinutes: 25,
      cookMinutes: 70,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Économique'],
      ingredients: [
        _ing('Haricots', 400, 'g', 3),
        _ing('Tripes', 500, 'g', 15),
      ],
    ),
    _recipe(
      name: 'Moules ail citron',
      description: 'Moules express à l\'ail et citron',
      emoji: '🦪',
      prepMinutes: 10,
      cookMinutes: 15,
      basePersons: 4,
      isHalal: true,
      isVegetarian: false,
      tags: ['Halal', 'Rapide'],
      ingredients: [
        _ing('Moules', 400, 'g', 25),
        _ing('Citron', 1, 'pièce(s)', 300),
        _ing('Ail', 2, 'pièce(s)', 1),
      ],
    ),
    _recipe(
      name: 'Zébu coco ravitoto',
      description: 'Zébu au coco et feuilles de manioc pilées',
      emoji: '🥥',
      prepMinutes: 30,
      cookMinutes: 90,
      basePersons: 4,
      isHalal: false,
      isVegetarian: false,
      tags: ['Traditionnel', 'Savoureux'],
      ingredients: [
        _ing('Zébu', 600, 'g', 20),
        _ing('Feuilles de manioc (ravitoto)', 300, 'g', 5),
        _ing('Lait de coco', 200, 'ml', 3),
      ],
    ),
    _recipe(
      name: 'Poulet brèdes cresson romazava',
      description: 'Romazava au poulet et brèdes cresson',
      emoji: '🍲',
      prepMinutes: 20,
      cookMinutes: 50,
      basePersons: 4,
      isHalal: true,
      isVegetarian: false,
      tags: ['Halal', 'Traditionnel', 'Familial'],
      ingredients: [
        _ing('Poulet', 600, 'g', 15),
        _ing('Brèdes cresson', 300, 'g', 2),
        _ing('Gingembre', 10, 'g', 5),
      ],
    ),
  ];
}